### ISSUE TITLE
Fix substitution for variables reused more than once.

### ISSUE THREAD

**Issue by ergawy** [KareemErgawy/types-and-programming-languages#2]
Related are the tests added by @Blaisorblade in this PR: https://github.com/KareemErgawy/types-and-programming-languages/pull/1.

**Comment by ergawy** [comment]
Hopefully fixed by: https://github.com/KareemErgawy/types-and-programming-languages/commit/76b0eabe54eaae4d8ec9db9f2bf9c127aecb7250.

**Comment by Blaisorblade** [comment]
Yeah, that looks correct to me :-). Cheers!
